### ISSUE TITLE
Support higher quality resolution for facebook

### ISSUE THREAD

**Issue by wankio** [Mordo95/video-downloader#1]
[facebook ](https://www.facebook.com/watch/?v=812500503135011)

for default i think it only work with 720p ?
there's 640-840-960-1080-1440p

**Comment by Mordo95** [comment]
there's only a `hdSrc` and `sdSrc` on the video player fiber, no idea what qualities they are. Default download is set on `hdSrc` which is I suppose what highest quality it offers.
